name: CI/CD Microservicio Usuario

on:
  push:
    branches: [ main ]

env:
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/servicio-usuario:latest

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Instalar Dependencias de Sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev gcc

      - name: Instalar Dependencias de Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Ejecutar Tests
        # Aquí es donde GitHub entra a tu carpeta usuario/tests.py
        run: python manage.py test usuario

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build y Push de la Imagen
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Aquí iría tu lógica de Terraform para actualizar la EC2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0
          
      # Terraform hará que la EC2 ejecute el docker-compose con la nueva imagen
      - name: Terraform Apply
        env:
          # Credenciales de AWS para que Terraform pueda crear recursos
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

          # Inyección de variables a Terraform (Secrets -> TF_VAR)
          TF_VAR_db_name: ${{ secrets.DB_NAME }}
          TF_VAR_db_user: ${{ secrets.DB_USER }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_django_secret_key: ${{ secrets.DJANGO_SECRET_KEY }}
          TF_VAR_docker_image: ${{ env.DOCKER_IMAGE }} # Esta viene de la variable de entorno del job
        run: |
          cd infra/terraform
          terraform init
          terraform apply -auto-approve